"""50+ original prompts for Lampoon, plus final-round prompts.

All prompts are original content.
"""

ROUND_PROMPTS: list[str] = [
    "The worst thing you could say at a job interview",
    "What your cat is actually thinking when it stares at you",
    "The world's most useless superpower",
    "A terrible name for a children's book",
    "The worst tagline for a dentist's office",
    "Something you'd find in a haunted Ikea",
    "An app that nobody asked for but someone will still make",
    "A bad first sentence for a romance novel",
    "The real reason dinosaurs went extinct",
    "The worst name for a new cryptocurrency",
    "A self-help book title that would make things worse",
    "Something you should never say to a wedding photographer",
    "The most passive-aggressive sticky note you could leave in an office kitchen",
    "A rejected name for the internet",
    "What the moon is actually made of",
    "The worst advice you could give a new parent",
    "A terrible slogan for a funeral home",
    "What aliens really think about humans",
    "An activity that sounds fun but definitely isn't",
    "The worst thing to shout in a library",
    "A sign that your GPS is having a bad day",
    "The worst power a superhero could have",
    "Something you really shouldn't put in a birthday card",
    "A bad excuse for being late to your own wedding",
    "The least motivating motivational poster",
    "A terrible name for a cooking show",
    "What your houseplants would say if they could talk",
    "The worst flavor of ice cream that someone would still sell",
    "An unlikely ingredient for a love potion",
    "The worst thing to say when someone shows you their new baby",
    "A rejected Hallmark movie title",
    "What the number zero dreams about at night",
    "The world's least extreme extreme sport",
    "A poorly timed joke to tell at a job interview",
    "Something that sounds polite but really isn't",
    "The worst advice column answer to 'I'm lonely'",
    "A business idea so bad it just might work",
    "An instruction you'd only find in the world's worst IKEA manual",
    "The worst thing a tour guide could say",
    "A new Olympic sport that will never be accepted",
    "The real reason the chicken crossed the road",
    "Something a time traveller would regret bringing back",
    "A terrible sequel title for a classic movie",
    "The worst mascot for a health food brand",
    "What pigeons are planning when they gather on a roof",
    "A skill nobody should put on their CV",
    "The worst career advice you've ever received",
    "A terrible name for a relaxation app",
    "The most suspicious thing to Google",
    "Something a ghost would complain about in a haunted house",
    "The least impressive magic trick",
    "A fortune cookie message that would make things worse",
    "The worst name for a new country",
    "What your WiFi password secretly means",
    "A bad title for a memoir about your daily commute",
]

FINAL_PROMPTS: list[str] = [
    "If you could add one ridiculous law, what would it be?",
    "What would be the worst theme for a restaurant that people would still go to?",
    "What is the most suspicious sentence to text someone out of nowhere?",
    "What would the world's worst theme park be called, and what's its main attraction?",
    "If you had to invent a new holiday, what pointless thing would it celebrate?",
    "What's the worst piece of advice you'd give to someone moving to a new city?",
    "What would you name a band if your name was a combination of your last meal and your current mood?",
    "What would the world's most unhelpful chatbot say in response to every question?",
]
